# Generated by Django 4.0.3 on 2022-05-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_client_date_created_alter_client_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
