# Generated by Django 4.0.3 on 2022-05-23 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_product_product_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='invoice',
            new_name='invoices',
        ),
    ]
