# Generated by Django 4.0.3 on 2022-05-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_client_email_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brandname'),
        ),
    ]
