# Generated by Django 4.0.3 on 2022-05-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_rename_invoice_product_invoices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_no',
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
